version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - mlruns:/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:///mlruns
      --default-artifact-root file:///mlruns
      --serve-artifacts
    

  airflow-webserver:
    build:
      context: ../airflow
      dockerfile: Dockerfile
    image: custom-airflow:2.7.1
    container_name: airflow-webserver
    user: "0:0"
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    env_file:
      - ../.env
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/include:/opt/airflow/include
      - ../data:/opt/airflow/data
      - mlruns:/mlruns
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    image: custom-airflow:2.7.1
    container_name: airflow-scheduler
    user: "0:0"
    depends_on:
      airflow-webserver:
        condition: service_started
    env_file:
      - ../.env
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/include:/opt/airflow/include
      - ../data:/opt/airflow/data
      - mlruns:/mlruns
    command: airflow scheduler

  inference:
    build:
      context: ../inference
    container_name: inference-service
    depends_on:
      mlflow:
        condition: service_started
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: california-housing
      MLFLOW_MODEL_NAME: california_housing_model
      MODEL_ALIAS: production
    volumes:
     - mlruns:/mlruns
    ports:
     - "8000:8000"

  jenkins:
    build:
      context: ../jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  postgres-db:
  mlruns:
  jenkins_home:
